FROM node:20-alpine

WORKDIR /app

# Copy package files separately to leverage caching
COPY package.json package-lock.json ./
RUN npm install

# Copy all other files
COPY . .

# Start React dev server
CMD ["npm", "start"]
