# Generated by Django 4.2.8 on 2024-07-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treemoisturecontent',
            old_name='value',
            new_name='value_test',
        ),
    ]
