# Generated by Django 4.2.8 on 2024-07-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_rename_value_treemoisturecontent_value_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treemoisturecontent',
            old_name='value_test',
            new_name='value',
        ),
    ]
