# Generated by Django 4.2.8 on 2024-07-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0005_electricalresistancereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHealthReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('health_status', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_readings', to='sensor_data.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
