# Generated by Django 4.2.8 on 2024-07-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0007_remove_treehealthreading_health_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('air_pressure', models.FloatField()),
                ('uv', models.FloatField()),
                ('luminosity', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='sensor_data.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
