# Generated by Django 4.2.8 on 2024-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0008_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='rainfall_counter',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
