# Generated by Django 4.2.8 on 2024-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0009_weatherdata_rainfall_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='luminosity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='uv',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
