# Generated by Django 4.2.8 on 2024-07-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0011_soilmoisturereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='pHReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ph_value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_readings', to='sensor_data.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
