# 1. Use a lightweight Python image
FROM python:3.9-slim

# 2. Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Set work directory
WORKDIR /django_backend

# 4. Install system dependencies (for mysqlclient, psycopg2, etc.)
RUN apt-get update \
    && apt-get install -y build-essential default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

# 5. Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copy project files
COPY . .

# 7. Expose port
EXPOSE 8000

# 8. Run server (dev mode)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
